# Generated by Django 4.2.2 on 2023-06-07 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_rename_home_welcomemessages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WelcomeMessages',
            new_name='WelcomeMessage',
        ),
    ]
